export const basePalabras = {
    REALISTA: { id: 'REALISTA', palabra: 'Realista', c: 0, d: 0, b: 0, a: 3 },
    PENSAMIENTO_RIGUROSO: { id: 'PENSAMIENTO_RIGUROSO', palabra: 'Pensamiento riguroso', c: 0, d: 0, b: 0, a: 1 },
    ANALITICO: { id: 'ANALITICO', palabra: 'Analítico', c: 0, d: 0, b: 0, a: 2 },
    INTERPRETATIVO: { id: 'INTERPRETATIVO', palabra: 'Interpretativo', c: 0, d: 1, b: 0, a: 1 },
    ESTRUCTURAL: { id: 'ESTRUCTURAL', palabra: 'Estructural', c: 0, d: 1, b: 0, a: 2 },
    DIAGNOSTICO: { id: 'DIAGNOSTICO', palabra: 'Diagnóstico', c: 0, d: 0, b: 0, a: 2 },
    CONCRETO: { id: 'CONCRETO', palabra: 'Concreto', c: 0, d: 0, b: 2, a: 2 },
    CRITICO: { id: 'CRITICO', palabra: 'Crítico', c: 0, d: 0, b: 0, a: 3 },
    LOGICO: { id: 'LOGICO', palabra: 'Lógico', c: 0, d: 0, b: 0, a: 2 },
    IDEALISTA: { id: 'IDEALISTA', palabra: 'Idealista', c: 0, d: 2, b: 0, a: 0 },
    IMAGINATIVO: { id: 'IMAGINATIVO', palabra: 'Imaginativo', c: 0, d: 3, b: 0, a: 0 },
    SINTETICO: { id: 'SINTETICO', palabra: 'Sintético', c: 0, d: 2, b: 0, a: 0 },
    INTEGRADOR: { id: 'INTEGRADOR', palabra: 'Integrador', c: 0, d: 2, b: 0, a: 0 },
    ESTRATEGA: { id: 'ESTRATEGA', palabra: 'Estratega', c: 0, d: 2, b: 0, a: 0 },
    INTUITIVO: { id: 'INTUITIVO', palabra: 'Intuitivo', c: 2, d: 1, b: 0, a: 0 },
    CINESTESICO: { id: 'CINESTESICO', palabra: 'Cinestésico', c: 1, d: 2, b: 0, a: 0 },
    MANUAL: { id: 'MANUAL', palabra: 'Manual', c: 0, d: 0, b: 1, a: 0 },
    PLANIFICADOR: { id: 'PLANIFICADOR', palabra: 'Planificador', c: 0, d: 0, b: 3, a: 0 },
    IMPLEMENTADOR: { id: 'IMPLEMENTADOR', palabra: 'Implementador', c: 0, d: 0, b: 2, a: 0 },
    SENSIBLE: { id: 'SENSIBLE', palabra: 'Sensible', c: 3, d: 0, b: 0, a: 0 },
    MUSICAL: { id: 'MUSICAL', palabra: 'Musical', c: 2, d: 0, b: 0, a: 0 },
    TACTIL: { id: 'TACTIL', palabra: 'Táctil', c: 3, d: 0, b: 0, a: 0 },
    AMIGABLE: { id: 'AMIGABLE', palabra: 'Amigable', c: 3, d: 0, b: 0, a: 0 },
    REPETITIVO: { id: 'REPETITIVO', palabra: 'Repetitivo', c: 0, d: 0, b: 2, a: 0 },
    SECUENCIAL: { id: 'SECUENCIAL', palabra: 'Secuencial', c: 0, d: 0, b: 2, a: 0 },
    PUNTUAL: { id: 'PUNTUAL', palabra: 'Puntual', c: 0, d: 0, b: 2, a: 0 },
    PROCESAL: { id: 'PROCESAL', palabra: 'Procesal', c: 0, d: 0, b: 1, a: 0 },
    INTERPERSONAL: { id: 'INTERPERSONAL', palabra: 'Interpersonal ', c: 3, d: 0, b: 0, a: 0 },
    EMOCIONAL: { id: 'EMOCIONAL', palabra: 'Emocional', c: 2, d: 0, b: 0, a: 0 },
    SOCIAL: { id: 'SOCIAL', palabra: 'Social', c: 3, d: 0, b: 0, a: 0 },
    ORGANIZADO: { id: 'ORGANIZADO', palabra: 'Organizado', c: 0, d: 0, b: 3, a: 0 },
    DETALLADO: { id: 'DETALLADO', palabra: 'Detallado', c: 0, d: 0, b: 3, a: 0 },
    CIENTIFICO: { id: 'CIENTIFICO', palabra: 'Científico', c: 0, d: 0, b: 0, a: 2 },
    MATEMATICO: { id: 'MATEMATICO', palabra: 'Matemático', c: 0, d: 0, b: 0, a: 2 },
    ESTADISTICO: { id: 'ESTADISTICO', palabra: 'Estadístico', c: 0, d: 0, b: 0, a: 2 },
    SERVICIAL: { id: 'SERVICIAL', palabra: 'Servicial', c: 1, d: 0, b: 0, a: 0 },
    RECOPILADOR: { id: 'RECOPILADOR', palabra: 'Recopilador', c: 0, d: 0, b: 2, a: 0 },
    CUIDADOSO: { id: 'CUIDADOSO', palabra: 'Cuidadoso', c: 0, d: 0, b: 2, a: 0 },
    APLICADO: { id: 'APLICADO', palabra: 'Aplicado', c: 0, d: 0, b: 2, a: 0 },
    TEORICO: { id: 'TEORICO', palabra: 'Teórico', c: 0, d: 0, b: 0, a: 2 },
    INTELECTUAL: { id: 'INTELECTUAL', palabra: 'Intelectual', c: 0, d: 2, b: 0, a: 3 },
    RESUELVE_PROBLEMAS: { id: 'RESUELVE_PROBLEMAS', palabra: 'Resuelve Problemas', c: 0, d: 0, b: 0, a: 3 },
    FINANCIERO: { id: 'FINANCIERO', palabra: 'Financiero', c: 0, d: 0, b: 0, a: 3 },
    CONSTRUCTIVO: { id: 'CONSTRUCTIVO', palabra: 'Constructivo', c: 1, d: 1, b: 1, a: 1 },
    VISUAL: { id: 'VISUAL', palabra: 'Visual', c: 0, d: 2, b: 0, a: 0 },
    CURIOSO: { id: 'CURIOSO', palabra: 'Curioso', c: 0, d: 3, b: 0, a: 0 },
    COMERCIAL: { id: 'COMERCIAL', palabra: 'Comercial', c: 0, d: 1, b: 0, a: 0 },
    SIMULTANEO: { id: 'SIMULTANEO', palabra: 'Simultaneo', c: 0, d: 2, b: 0, a: 0 },
    COMUNICADOR: { id: 'COMUNICADOR', palabra: 'Comunicador', c: 2, d: 2, b: 0, a: 0 },
    ARTISTICO: { id: 'ARTISTICO', palabra: 'Artístico', c: 0, d: 3, b: 0, a: 0 },
    ARRIESGADO: { id: 'ARRIESGADO', palabra: 'Arriesgado', c: 0, d: 2, b: 0, a: 0 },
    FACILITADOR: { id: 'FACILITADOR', palabra: 'Facilitador', c: 2, d: 0, b: 0, a: 0 },
    DIDACTICO: { id: 'DIDACTICO', palabra: 'Didáctico', c: 1, d: 1, b: 0, a: 0 },
    COORDINADOR: { id: 'COORDINADOR', palabra: 'Coordinador', c: 1, d: 0, b: 1, a: 0 },
    CONCILIADOR: { id: 'CONCILIADOR', palabra: 'Conciliador', c: 2, d: 0, b: 0, a: 0 },
    GUSTA_DE_SORPRESAS: { id: 'GUSTA_DE_SORPRESAS', palabra: 'Gusta de sorpresas', c: 0, d: 1, b: 0, a: 0 },
    ESPIRITUAL: { id: 'ESPIRITUAL', palabra: 'Espiritual', c: 2, d: 0, b: 0, a: 0 },
    METAFORICO: { id: 'METAFORICO', palabra: 'Metaforico', c: 0, d: 2, b: 0, a: 0 },
    EMPATICO: { id: 'EMPATICO', palabra: 'Empatíco', c: 3, d: 0, b: 0, a: 0 },
    TRADICIONAL: { id: 'TRADICIONAL', palabra: 'Tradicional', c: 0, d: 0, b: 2, a: 0 },
    CONVERSADOR: { id: 'CONVERSADOR', palabra: 'Conversador', c: 2, d: 0, b: 0, a: 0 },
    CATEGORICO: { id: 'CATEGORICO', palabra: 'Categórico', c: 0, d: 0, b: 1, a: 0 },
    PREVENTIVO: { id: 'PREVENTIVO', palabra: 'Preventivo', c: 0, d: 0, b: 2, a: 0 },
    CAUTELOSO: { id: 'CAUTELOSO', palabra: 'Cauteloso', c: 0, d: 0, b: 1, a: 0 },
    SIGUE_REGLAS: { id: 'SIGUE_REGLAS', palabra: 'Sigue reglas', c: 0, d: 0, b: 1, a: 0 },
    DECIDIDO: { id: 'DECIDIDO', palabra: 'Decidido', c: 0, d: 0, b: 0, a: 2 },
    ADMINISTRADOR: { id: 'ADMINISTRADOR', palabra: 'Administrador', c: 0, d: 0, b: 3, a: 0 },
    DISPUESTO: { id: 'DISPUESTO', palabra: 'Dispuesto', c: 1, d: 0, b: 0, a: 0 },
    EXPRESIVO: { id: 'EXPRESIVO', palabra: 'Expresivo', c: 2, d: 0, b: 0, a: 0 },
    CONTROLADOR: { id: 'CONTROLADOR', palabra: 'Controlador', c: 0, d: 0, b: 2, a: 0 },
    INNOVADOR: { id: 'INNOVADOR', palabra: 'Innovador', c: 0, d: 3, b: 0, a: 0 },
    IMPETUOSO: { id: 'IMPETUOSO', palabra: 'Impetuoso', c: 0, d: 2, b: 0, a: 0 },
    CREATIVO: { id: 'CREATIVO', palabra: 'Creativo', c: 0, d: 3, b: 0, a: 0 },
    DISCIPLINADO: { id: 'DISCIPLINADO', palabra: 'Disciplinado', c: 0, d: 0, b: 3, a: 0 },
    METODICO: { id: 'METODICO', palabra: 'Metódico', c: 0, d: 0, b: 2, a: 0 },
    SUPERVISOR: { id: 'SUPERVISOR', palabra: 'Supervisor', c: 0, d: 0, b: 2, a: 0 },
    CONSERVADOR: { id: 'CONSERVADOR', palabra: 'Conservador', c: 0, d: 0, b: 2, a: 0 },
    LECTOR: { id: 'LECTOR', palabra: 'Lector', c: 1, d: 0, b: 1, a: 0 },
    TERMINA_TAREAS: { id: 'TERMINA_TAREAS', palabra: 'Termina tareas', c: 0, d: 0, b: 3, a: 0 },
    DOCUMENTADO: { id: 'DOCUMENTADO', palabra: 'Documentado', c: 0, d: 0, b: 0, a: 1 },
    DIRECTIVO: { id: 'DIRECTIVO', palabra: 'Directivo', c: 0, d: 0, b: 0, a: 2 },
    RELACIONAL: { id: 'RELACIONAL', palabra: 'Relacional', c: 3, d: 0, b: 0, a: 0 },
    TECNICO: { id: 'TECNICO', palabra: 'Técnico', c: 0, d: 0, b: 0, a: 1 },
    INVESTIGADOR: { id: 'INVESTIGADOR', palabra: 'Investigador', c: 0, d: 0, b: 0, a: 2 },
    ELOCUENTE: { id: 'ELOCUENTE', palabra: 'Elocuente', c: 0, d: 2, b: 0, a: 1 },
    RACIONAL: { id: 'RACIONAL', palabra: 'Racional', c: 0, d: 0, b: 0, a: 3 },
    CUANTITATIVO: { id: 'CUANTITATIVO', palabra: 'Cuantitativo', c: 0, d: 0, b: 0, a: 3 },
    RESOLUTIVO: { id: 'RESOLUTIVO', palabra: 'Resolutivo', c: 0, d: 0, b: 2, a: 2 },
    GUSTA_ENSEÑAR: { id: 'GUSTA_ENSEÑAR', palabra: 'Gusta enseñar', c: 2, d: 0, b: 0, a: 0 },
    INVENTOR: { id: 'INVENTOR', palabra: 'Inventor', c: 0, d: 1, b: 0, a: 0 },
    LIDERAZGO: { id: 'LIDERAZGO', palabra: 'Liderazgo', c: 0, d: 2, b: 0, a: 0 },
    SIMBOLICO: { id: 'SIMBOLICO', palabra: 'Simbolico', c: 1, d: 0, b: 0, a: 0 },
    EMPRENDEDOR: { id: 'EMPRENDEDOR', palabra: 'Emprendedor', c: 0, d: 2, b: 0, a: 0 },
    DIVERTIDO: { id: 'DIVERTIDO', palabra: 'Divertido', c: 0, d: 2, b: 0, a: 0 },
    FLEXIBLE: { id: 'FLEXIBLE', palabra: 'Flexible', c: 2, d: 0, b: 0, a: 0 },
    COMPRENSIVO: { id: 'COMPRENSIVO', palabra: 'Comprensivo', c: 1, d: 0, b: 0, a: 0 },
    POR_ESCRITO: { id: 'POR_ESCRITO', palabra: 'Por escrito', c: 1, d: 0, b: 1, a: 0 },
    HOLISTICO: { id: 'HOLISTICO', palabra: 'Holistico', c: 0, d: 2, b: 0, a: 0 },
    PERSUASIVO: { id: 'PERSUASIVO', palabra: 'Persuasivo', c: 1, d: 0, b: 0, a: 0 },
    ESCUCHA_ACTIVA: { id: 'ESCUCHA_ACTIVA', palabra: 'Escucha activa', c: 3, d: 0, b: 0, a: 0 },
    CALCULADOR: { id: 'CALCULADOR', palabra: 'Calculador', c: 0, d: 0, b: 0, a: 1 },
    PRACTICO: { id: 'PRACTICO', palabra: 'Practico', c: 0, d: 0, b: 0, a: 1 },
    INVENTIVO: { id: 'INVENTIVO', palabra: 'Inventivo', c: 0, d: 0, b: 0, a: 1 },
    PRECISO: { id: 'PRECISO', palabra: 'Preciso', c: 0, d: 0, b: 0, a: 1 },
};

export const mapa1 = [
    basePalabras['REALISTA'],
    basePalabras['PENSAMIENTO_RIGUROSO'],
    basePalabras['ANALITICO'],
    basePalabras['INTERPRETATIVO'],
    basePalabras['ESTRUCTURAL'],
    basePalabras['DIAGNOSTICO'],
    basePalabras['CONCRETO'],
    basePalabras['CRITICO'],
    basePalabras['LOGICO'],
    basePalabras['IDEALISTA'],
    basePalabras['IMAGINATIVO'],
    basePalabras['SINTETICO'],
    basePalabras['INTEGRADOR'],
    basePalabras['ESTRATEGA'],
    basePalabras['INTUITIVO'],
    basePalabras['CINESTESICO'],
    basePalabras['MANUAL'],
    basePalabras['PLANIFICADOR'],
    basePalabras['IMPLEMENTADOR'],
    basePalabras['SENSIBLE'],
    basePalabras['MUSICAL'],
    basePalabras['TACTIL'],
    basePalabras['AMIGABLE'],
    basePalabras['REPETITIVO'],
    basePalabras['SECUENCIAL'],
    basePalabras['PUNTUAL'],
    basePalabras['CAUTELOSO'],
    basePalabras['SIGUE_REGLAS'],
    basePalabras['DECIDIDO'],
    basePalabras['PROCESAL'],
    basePalabras['INTERPERSONAL'],
];

export const mapa2 = [
    basePalabras['EMOCIONAL'],
    basePalabras['SOCIAL'],
    basePalabras['ORGANIZADO'],
    basePalabras['DETALLADO'],
    basePalabras['CIENTIFICO'],
    basePalabras['MATEMATICO'],
    basePalabras['ESTADISTICO'],
    basePalabras['SERVICIAL'],
    basePalabras['RECOPILADOR'],
    basePalabras['CUIDADOSO'],
    basePalabras['APLICADO'],
    basePalabras['TEORICO'],
    basePalabras['INTELECTUAL'],
    basePalabras['RESUELVE_PROBLEMAS'],
    basePalabras['FINANCIERO'],
    basePalabras['CONSTRUCTIVO'],
    basePalabras['VISUAL'],
    basePalabras['CURIOSO'],
    basePalabras['COMERCIAL'],
    basePalabras['SIMULTANEO'],
    basePalabras['COMUNICADOR'],
    basePalabras['ARTISTICO'],
    basePalabras['ARRIESGADO'],
    basePalabras['FACILITADOR'],
    basePalabras['DIDACTICO'],
    basePalabras['COORDINADOR'],
    basePalabras['CONCILIADOR'],
    basePalabras['GUSTA_DE_SORPRESAS'],
    basePalabras['ESPIRITUAL'],
    basePalabras['METAFORICO'],
    basePalabras['EMPATICO'],
    basePalabras['TRADICIONAL'],
    basePalabras['CONVERSADOR'],
    basePalabras['CATEGORICO'],
    basePalabras['PREVENTIVO'],
];

export const mapa3 = [
    basePalabras['ADMINISTRADOR'],
    basePalabras['DISPUESTO'],
    basePalabras['EXPRESIVO'],
    basePalabras['CONTROLADOR'],
    basePalabras['INNOVADOR'],
    basePalabras['IMPETUOSO'],
    basePalabras['CREATIVO'],
    basePalabras['DISCIPLINADO'],
    basePalabras['METODICO'],
    basePalabras['SUPERVISOR'],
    basePalabras['CONSERVADOR'],
    basePalabras['LECTOR'],
    basePalabras['TERMINA_TAREAS'],
    basePalabras['DOCUMENTADO'],
    basePalabras['DIRECTIVO'],
    basePalabras['RELACIONAL'],
    basePalabras['TECNICO'],
    basePalabras['INVESTIGADOR'],
    basePalabras['ELOCUENTE'],
    basePalabras['RACIONAL'],
    basePalabras['CUANTITATIVO'],
    basePalabras['RESOLUTIVO'],
    basePalabras['GUSTA_ENSEÑAR'],
    basePalabras['INVENTOR'],
    basePalabras['LIDERAZGO'],
    basePalabras['SIMBOLICO'],
    basePalabras['EMPRENDEDOR'],
    basePalabras['DIVERTIDO'],
    basePalabras['FLEXIBLE'],
    basePalabras['COMPRENSIVO'],
    basePalabras['POR_ESCRITO'],
    basePalabras['HOLISTICO'],
    basePalabras['PERSUASIVO'],
    basePalabras['ESCUCHA_ACTIVA'],
    basePalabras['CALCULADOR'],
    basePalabras['PRACTICO'],
    basePalabras['INVENTIVO'],
    basePalabras['PRECISO'],
];
